const quillTr = new Quill("#editorTr", { theme: "snow" });
const quillEn = new Quill("#editorEn", { theme: "snow" });

let posts = [];
let selectedPostId = null;
let coverImageUrl = "";
let attachments = [];
let slugAutoGenerated = "";

function slugify(text) {
  return (text || "")
    .toLowerCase()
    .replace(/ğ/g, "g").replace(/ü/g, "u").replace(/ş/g, "s")
    .replace(/ı/g, "i").replace(/ö/g, "o").replace(/ç/g, "c")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

// ---- Lang tabs ----
document.querySelectorAll(".lang-tab").forEach(tab => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".lang-tab").forEach(t => t.classList.remove("active"));
    document.querySelectorAll(".lang-pane").forEach(p => p.classList.remove("active"));
    tab.classList.add("active");
    document.querySelector(`[data-lang-pane="${tab.dataset.lang}"]`).classList.add("active");
  });
});

// ---- List ----
async function loadPosts() {
  const { data, error } = await sb.from("blog_posts").select("*").order("created_at", { ascending: false });
  if (error) { console.error(error); return; }
  posts = data || [];
  renderList();
}

function renderList() {
  const list = document.getElementById("postList");
  list.innerHTML = "";
  posts.forEach(post => {
    const item = document.createElement("div");
    item.className = "admin-list-item" + (post.id === selectedPostId ? " active" : "");
    item.innerHTML = `
      <span class="title">${escapeHtml(post.title_tr || "(Başlıksız)")}</span>
      <span class="meta"><span class="status-dot ${post.published ? "published" : "draft"}"></span>${post.published ? "Yayında" : "Taslak"}</span>
    `;
    item.addEventListener("click", () => selectPost(post.id));
    list.appendChild(item);
  });
}

function escapeHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}

// ---- Form ----
function resetForm() {
  selectedPostId = null;
  coverImageUrl = "";
  attachments = [];
  slugAutoGenerated = "";
  document.getElementById("titleTr").value = "";
  document.getElementById("titleEn").value = "";
  document.getElementById("excerptTr").value = "";
  document.getElementById("excerptEn").value = "";
  document.getElementById("slug").value = "";
  document.getElementById("published").checked = false;
  quillTr.setContents([]);
  quillEn.setContents([]);
  document.getElementById("coverPreview").style.display = "none";
  document.getElementById("deleteBtn").style.display = "none";
  document.getElementById("attachmentInput").disabled = true;
  document.getElementById("statusMsg").textContent = "";
  renderAttachments();
  renderList();
}

async function selectPost(id) {
  const post = posts.find(p => p.id === id);
  if (!post) return;
  selectedPostId = post.id;
  coverImageUrl = post.cover_image_url || "";
  document.getElementById("titleTr").value = post.title_tr || "";
  document.getElementById("titleEn").value = post.title_en || "";
  document.getElementById("excerptTr").value = post.excerpt_tr || "";
  document.getElementById("excerptEn").value = post.excerpt_en || "";
  document.getElementById("slug").value = post.slug || "";
  document.getElementById("published").checked = !!post.published;
  quillTr.root.innerHTML = post.body_tr || "";
  quillEn.root.innerHTML = post.body_en || "";
  const preview = document.getElementById("coverPreview");
  if (coverImageUrl) { preview.src = coverImageUrl; preview.style.display = "block"; }
  else { preview.style.display = "none"; }
  document.getElementById("deleteBtn").style.display = "inline-block";
  document.getElementById("attachmentInput").disabled = false;

  const { data } = await sb.from("blog_attachments").select("*").eq("post_id", post.id);
  attachments = data || [];
  renderAttachments();
  renderList();
}

function renderAttachments() {
  const wrap = document.getElementById("attachmentList");
  wrap.innerHTML = "";
  attachments.forEach(att => {
    const chip = document.createElement("div");
    chip.className = "file-chip";
    chip.innerHTML = `<span>${escapeHtml(att.file_name || att.file_url)}</span>`;
    const removeBtn = document.createElement("button");
    removeBtn.type = "button";
    removeBtn.textContent = "✕";
    removeBtn.addEventListener("click", () => removeAttachment(att));
    chip.appendChild(removeBtn);
    wrap.appendChild(chip);
  });
}

async function removeAttachment(att) {
  if (att.id) {
    await sb.from("blog_attachments").delete().eq("id", att.id);
  }
  attachments = attachments.filter(a => a !== att);
  renderAttachments();
}

document.getElementById("titleTr").addEventListener("input", (e) => {
  const slugEl = document.getElementById("slug");
  if (!slugEl.value || slugEl.value === slugAutoGenerated) {
    slugAutoGenerated = slugify(e.target.value);
    slugEl.value = slugAutoGenerated;
  }
});

document.getElementById("newPostBtn").addEventListener("click", resetForm);

document.getElementById("coverInput").addEventListener("change", async (e) => {
  const file = e.target.files[0];
  if (!file) return;
  const path = `${Date.now()}-${file.name}`;
  const { error } = await sb.storage.from("blog-media").upload(path, file);
  if (error) { showStatus("Görsel yüklenemedi: " + error.message, false); return; }
  const { data } = sb.storage.from("blog-media").getPublicUrl(path);
  coverImageUrl = data.publicUrl;
  const preview = document.getElementById("coverPreview");
  preview.src = coverImageUrl;
  preview.style.display = "block";
});

document.getElementById("attachmentInput").addEventListener("change", async (e) => {
  const file = e.target.files[0];
  if (!file || !selectedPostId) return;
  const path = `${Date.now()}-${file.name}`;
  const { error } = await sb.storage.from("blog-files").upload(path, file);
  if (error) { showStatus("Dosya yüklenemedi: " + error.message, false); return; }
  const { data } = sb.storage.from("blog-files").getPublicUrl(path);
  const { data: inserted, error: insertError } = await sb
    .from("blog_attachments")
    .insert({ post_id: selectedPostId, file_url: data.publicUrl, file_name: file.name, file_type: file.type })
    .select()
    .single();
  if (insertError) { showStatus("Ek kaydedilemedi: " + insertError.message, false); return; }
  attachments.push(inserted);
  renderAttachments();
  e.target.value = "";
});

function showStatus(msg, ok) {
  const el = document.getElementById("statusMsg");
  el.textContent = msg;
  el.className = "status-msg " + (ok ? "ok" : "err");
}

document.getElementById("saveBtn").addEventListener("click", async () => {
  const payload = {
    title_tr: document.getElementById("titleTr").value,
    title_en: document.getElementById("titleEn").value,
    excerpt_tr: document.getElementById("excerptTr").value,
    excerpt_en: document.getElementById("excerptEn").value,
    body_tr: quillTr.root.innerHTML,
    body_en: quillEn.root.innerHTML,
    slug: document.getElementById("slug").value,
    published: document.getElementById("published").checked,
    cover_image_url: coverImageUrl
  };

  if (!payload.title_tr || !payload.slug) {
    showStatus("Başlık (TR) ve slug zorunludur.", false);
    return;
  }

  let result;
  if (selectedPostId) {
    result = await sb.from("blog_posts").update(payload).eq("id", selectedPostId).select().single();
  } else {
    result = await sb.from("blog_posts").insert(payload).select().single();
  }

  if (result.error) {
    showStatus("Kaydedilemedi: " + result.error.message, false);
    return;
  }

  selectedPostId = result.data.id;
  document.getElementById("deleteBtn").style.display = "inline-block";
  document.getElementById("attachmentInput").disabled = false;
  showStatus("Kaydedildi.", true);
  await loadPosts();
});

document.getElementById("deleteBtn").addEventListener("click", async () => {
  if (!selectedPostId) return;
  if (!confirm("Bu yazıyı silmek istediğinize emin misiniz?")) return;
  const { error } = await sb.from("blog_posts").delete().eq("id", selectedPostId);
  if (error) { showStatus("Silinemedi: " + error.message, false); return; }
  resetForm();
  await loadPosts();
});

document.addEventListener("DOMContentLoaded", loadPosts);
